name: CI
run-name: ${{ github.actor }} is running CI
on: [push]

permissions:
  actions: 'write'

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print Node.js version
        run: echo "Unit Tests"

  integration-tests:
    name: Integration Tests
    if: github.event_name == 'push' && contains(github.ref, 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect changes in migrations folder
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            migrations:
              - 'migrations/**'
        
      - if: steps.changes.outputs.migrations == 'false'
        name: Skip Integration Tests
        run: |
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }} # Watch is required as cancellation is not immediate
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Node.js version
        run: echo "Integration Tests"